export const presets = {
	defaultTheme: {
		'--sand-bg-color': '#000000',
		'--sand-text-color-rgb': '#E6E6E6',
		'--sand-text-sub-color': '#ABAEB3',
		'--sand-shadow-color-rgb': '#000000',
		'--sand-component-text-color-rgb': '#E6E6E6',
		'--sand-component-text-sub-color-rgb': '#ABAEB3',
		'--sand-component-bg-color': '#7D848C',
		'--sand-component-active-indicator-bg-color': '#E6E6E6',
		'--sand-component-inactive-indicator-bg-color': '#9DA2A7',
		'--sand-focus-text-color': '#FFFFFF',
		'--sand-focus-bg-color-rgb': '#E6E6E6',
		'--sand-component-focus-text-color-rgb': '#4C5059',
		'--sand-component-focus-active-indicator-bg-color': '#4C5059',
		'--sand-component-focus-inactive-indicator-bg-color': '#B8B9BB',
		'--sand-selected-color-rgb': '#E6E6E6',
		'--sand-selected-text-color': '#E6E6E6',
		'--sand-selected-bg-color': '#3E454D',
		'--sand-disabled-focus-bg-color': '#ABAEB3',
		'--sand-disabled-selected-color': '#4C5059',
		'--sand-disabled-selected-bg-color': '#E6E6E6',
		'--sand-disabled-selected-focus-color': '#E6E6E6',
		'--sand-disabled-selected-focus-bg-color': '#4C5059',
		'--sand-fullscreen-bg-color': '#000000',
		'--sand-overlay-bg-color-rgb': '#575E66',
		'--sand-selection-color': '#4C5059',
		'--sand-selection-bg-color': '#3399FF',
		'--sand-toggle-off-color': '#AEAEAE',
		'--sand-toggle-off-bg-color': '#777777',
		'--sand-toggle-on-color': '#E6E6E6',
		'--sand-toggle-on-bg-color': '#30AD6B',
		'--sand-progress-color-rgb': '#E6E6E6',
		'--sand-progress-buffer-color': '#6B6D73',
		'--sand-progress-bg-color-rgb': '#373A41',
		'--sand-progress-highlighted-color': '#FFFFFF',
		'--sand-progress-slider-color': '#8D9298',
		'--sand-spinner-color': '#FFFFFF',
		'--sand-checkbox-color': '#E6E6E6',
		'--sand-item-disabled-focus-bg-color': '#E6E6E6',
		'--sand-keyguide-bg-color-rgb': '#6B6D73',
		'--sand-slider-disabled-knob-bg-color': '#666666',
		'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
		'--sand-alert-overlay-text-color-rgb': '#2E3239',
		'--sand-alert-overlay-text-sub-color': '#2E3239',
		'--sand-alert-overlay-focus-text-color': '#575E66',
		'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
		'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
		'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
		'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
		'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
		'--sand-alert-overlay-progress-bg-color-rgb': '#A1A1A1',
		'--sand-alert-overlay-checkbox-color': '#858B92',
		'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
		'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
		'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	},
	blueColorSet1: {
		'--sand-bg-color': '#000000',
		'--sand-text-color-rgb': '#E6E6E6',
		'--sand-text-sub-color': '#ABAEB3',
		'--sand-shadow-color-rgb': '#000000',
		'--sand-component-text-color-rgb': '#E6E6E6',
		'--sand-component-text-sub-color-rgb': '#ABAEB3',
		'--sand-component-bg-color': '#7D848C',
		'--sand-component-active-indicator-bg-color': '#E6E6E6',
		'--sand-component-inactive-indicator-bg-color': '#9DA2A7',
		'--sand-focus-text-color': '#303030',
		'--sand-focus-bg-color-rgb': '#E6E6E6',
		'--sand-component-focus-text-color-rgb': '#333333',
		'--sand-component-focus-active-indicator-bg-color': '#4C5059',
		'--sand-component-focus-inactive-indicator-bg-color': '#B8B9BB',
		'--sand-selected-color-rgb': '#E6E6E6',
		'--sand-selected-text-color': '#E6E6E6',
		'--sand-selected-bg-color': '#61688E',
		'--sand-disabled-focus-bg-color': '#ABAEB3',
		'--sand-disabled-selected-color': '#FF0000',
		'--sand-disabled-selected-bg-color': '#FF0000',
		'--sand-disabled-selected-focus-color': '#FF0000',
		'--sand-disabled-selected-focus-bg-color': '#FF0000',
		'--sand-fullscreen-bg-color': '#000000',
		'--sand-overlay-bg-color-rgb': '#292929',
		'--sand-selection-color': '#4C5059',
		'--sand-selection-bg-color': '#3399FF',
		'--sand-toggle-off-color': '#AEAEAE',
		'--sand-toggle-off-bg-color': '#494949',
		'--sand-toggle-on-color': '#E6E6E6',
		'--sand-toggle-on-bg-color': '#61688E',
		'--sand-progress-color-rgb': '#E6E6E6',
		'--sand-progress-buffer-color': '#6B6D73',
		'--sand-progress-bg-color-rgb': '#373A41',
		'--sand-progress-highlighted-color': '#FFFFFF',
		'--sand-progress-slider-color': '#8D9298',
		'--sand-spinner-color': '#FFFFFF',
		'--sand-checkbox-color': '#E6E6E6',
		'--sand-item-disabled-focus-bg-color': '#E6E6E6',
		'--sand-keyguide-bg-color-rgb': '#6B6D73',
		'--sand-slider-disabled-knob-bg-color': '#666666',
		'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
		'--sand-alert-overlay-text-color-rgb': '#2E3239',
		'--sand-alert-overlay-text-sub-color': '#2E3239',
		'--sand-alert-overlay-focus-text-color': '#575E66',
		'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
		'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
		'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
		'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
		'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
		'--sand-alert-overlay-progress-bg-color-rgb': '#A1A1A1',
		'--sand-alert-overlay-checkbox-color': '#858B92',
		'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
		'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
		'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	},
	// greenColorSet1: {
	// 	'--sand-bg-color': '#272829',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color': '#ACB0B5',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#303030',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#4C5059',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#61838F',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#242424',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#AFB0B0',
	// 	'--sand-toggle-off-bg-color': '#474747',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#61838F',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// },
	// purpleColorSet1: {
	// 	'--sand-bg-color': '#272829',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color':'#ACB0B5',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#303030',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#4C5059',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#77618F',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#242424',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#AFB0B0',
	// 	'--sand-toggle-off-bg-color': '#474747',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#77618F',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// },
	// redColorSet1: {
	// 	'--sand-bg-color': '#252424',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color': '#ACB0B5',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#303030',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#4C5059',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#8F6161',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#242424',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#AFB0B0',
	// 	'--sand-toggle-off-bg-color': '#474747',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#8F6161',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// },
	// blueColorSet2: {
	// 	'--sand-bg-color': '#181E3D',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color': '#ACB0B5',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#152DAC',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#152DAC',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#61688F',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#29325E',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#797D91',
	// 	'--sand-toggle-off-bg-color': '#424B74',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#7C85B3',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// },
	// greenColorSet2: {
	// 	'--sand-bg-color': '#102933',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color': '#ACB0B5',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#02435F',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#02435F',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#61838F',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#1C3F4B',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#6F7F85',
	// 	'--sand-toggle-off-bg-color': '#2D4F5B',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#6B96A6',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// },
	// purpleColorSet2: {
	// 	'--sand-bg-color': '#2B1941',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color': '#858391',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#FFFFFF',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#4C128F',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#77618F',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#3A2752',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#81788D',
	// 	'--sand-toggle-off-bg-color': '#533F6C',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#8B76A3',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// },
	// redColorSet2: {
	// 	'--sand-bg-color': '#3D1A1A',
	// 	'--sand-text-color': '#E7E7E7',
	// 	'--sand-text-sub-color': '#817578',
	// 	'--sand-shadow-color-rgb': '#000000',
	// 	'--sand-component-text-color': '#E6E6E6',
	// 	'--sand-component-bg-color': '#7D848C',
	// 	'--sand-focus-text-color': '#851919',
	// 	'--sand-focus-bg-color': '#E7E7E7',
	// 	'--sand-component-focus-text-color-rgb': '#851919',
	// 	'--sand-selected-color-rgb': '#E6E6E6',
	// 	'--sand-selected-text-color': '#E6E6E6',
	// 	'--sand-selected-bg-color': '#8F6161',
	// 	'--sand-disabled-focus-bg-color': '#ABAEB3',
	// 	'--sand-disabled-selected-color': '#4C5059',
	// 	'--sand-disabled-selected-bg-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-fullscreen-bg-color': '#000000',
	// 	'--sand-overlay-bg-color-rgb': '#562121',
	// 	'--sand-selection-color': '#4C5059',
	// 	'--sand-selection-bg-color': '#3399FF',
	// 	'--sand-toggle-off-color': '#937B7B',
	// 	'--sand-toggle-off-bg-color': '#794545',
	// 	'--sand-toggle-on-color': '#E6E6E6',
	// 	'--sand-toggle-on-bg-color': '#BC7E7E',
	// 	'--sand-progress-color-rgb': '#E6E6E6',
	// 	'--sand-progress-buffer-color': '#6B6D73',
	// 	'--sand-progress-bg-color': '#373A41',
	// 	'--sand-progress-slider-color': '#8D9298',
	// 	'--sand-checkbox-color': '#E6E6E6',
	// 	'--sand-item-disabled-focus-bg-color': '#E6E6E6',
	// 	'--sand-keyguide-bg-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-bg-color-rgb': '#CACBCC',
	// 	'--sand-alert-overlay-text-color': '#2E3239',
	// 	'--sand-alert-overlay-text-sub-color': '#2E3239',
	// 	'--sand-alert-overlay-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-disabled-selected-bg-color': '#788688',
	// 	'--sand-alert-overlay-disabled-selected-focus-color': '#E6E6E6',
	// 	'--sand-alert-overlay-disabled-selected-focus-bg-color': '#4C5059',
	// 	'--sand-alert-overlay-progress-color-rgb': '#6B6D73',
	// 	'--sand-alert-overlay-progress-bg-color': '#A1A1A1',
	// 	'--sand-alert-overlay-checkbox-color': '#858B92',
	// 	'--sand-alert-overlay-checkbox-disabled-selected-color': '#FFFFFF',
	// 	'--sand-alert-overlay-formcheckboxitem-focus-text-color': '#575E66',
	// 	'--sand-alert-overlay-item-disabled-focus-bg-color': '#989CA2'
	// }
};
